config/routes.rb
Rails.application.routes.draw do
  resources :chars
  resources :skills
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/char.rb
class Char < ApplicationRecord
  has_many :char_skills, dependent: :destroy  
  has_many :skills, through: :char_skills

  def prof_bonus
    case lvl
    when 1..4 then 2
    when 5..8 then 3
    when 9..12 then 4
    when 13..16 then 5
    else 6
    end
  end
end

app/models/char_skill.rb
class CharSkill < ApplicationRecord
  belongs_to :char
  belongs_to :skill
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :char_skills, dependent: :destroy
    has_many :chars, through: :char_skills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chars_controller.rb
class CharsController < ApplicationController
  before_action :set_char, only: %i[ show edit update destroy ]

  # GET /chars or /chars.json
  def index
    @chars = Char.includes(:skills).all
  end
  

  # GET /chars/1 or /chars/1.json
  def show
  end

  # GET /chars/new
  def new
    @char = Char.new
  end

  # GET /chars/1/edit
  def edit
  end

  # POST /chars or /chars.json
  def create
    @char = Char.new(char_params)

    respond_to do |format|
      if @char.save
        format.html { redirect_to @char, notice: "Char was successfully created." }
        format.json { render :show, status: :created, location: @char }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chars/1 or /chars/1.json
  def update
    respond_to do |format|
      if @char.update(char_params)
        format.html { redirect_to @char, notice: "Char was successfully updated." }
        format.json { render :show, status: :ok, location: @char }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chars/1 or /chars/1.json
  def destroy
    @char.destroy!

    respond_to do |format|
      format.html { redirect_to chars_path, status: :see_other, notice: "Char was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_char
      @char = Char.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def char_params
      params.require(:char).permit(:name, :str, :dex, :con, :int, :wis, :cha, :lvl, skill_ids: [])
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]

  # GET /skills or /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1 or /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy!

    respond_to do |format|
      format.html { redirect_to skills_path, status: :see_other, notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.expect(skill: [ :name, :ability, :score, :proficient ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chars_helper.rb
module CharsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/chars/_char.html.erb
<tr id="<%= dom_id(char) %>">
  <td><%= char.name %></td>
  <td><%= char.str %></td>
  <td><%= char.dex %></td>
  <td><%= char.con %></td>
  <td><%= char.int %></td>
  <td><%= char.wis %></td>
  <td><%= char.cha %></td>
  <td><%= char.lvl %></td>
  <td><%= char.prof_bonus %></td>
  <td>
    <% if char.skills.present? %>
      <ul>
        <% char.skills.each do |skill| %>
          <li><%= skill.name %></li>
        <% end %>
      </ul>
    <% else %>
      None
    <% end %>
  </td>
  <td>
    <%= link_to 'Show this char', char_path(char), class: 'btn btn-primary' %>
  </td>
</tr>

app/views/chars/_form.html.erb
<%= form_with(model: char) do |form| %>
  <% if char.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(char.errors.count, "error") %> prohibited this char from being saved:</h2>

      <ul>
        <% char.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :str, style: "display: block" %>
    <%= form.number_field :str %>
  </div>

  <div>
    <%= form.label :dex, style: "display: block" %>
    <%= form.number_field :dex %>
  </div>

  <div>
    <%= form.label :con, style: "display: block" %>
    <%= form.number_field :con %>
  </div>

  <div>
    <%= form.label :int, style: "display: block" %>
    <%= form.number_field :int %>
  </div>

  <div>
    <%= form.label :wis, style: "display: block" %>
    <%= form.number_field :wis %>
  </div>

  <div>
    <%= form.label :cha, style: "display: block" %>
    <%= form.number_field :cha %>
  </div>

  <div>
    <%= form.label :lvl, style: "display: block" %>
    <%= form.number_field :lvl %>
  </div>
  
  <div>
    <%= form.label :skills %>
    <%= form.collection_select :skill_ids, Skill.all, :id, :name, {}, { multiple: true } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chars/edit.html.erb
<% content_for :title, "Editing char" %>

<h1>Editing char</h1>

<%= render "form", char: @char %>

<br>

<div>
  <%= link_to "Show this char", @char %> |
  <%= link_to "Back to chars", chars_path %>
</div>

app/views/chars/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Chars" %>

<h1>Chars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Str</th>
      <th>Dex</th>
      <th>Con</th>
      <th>Int</th>
      <th>Wis</th>
      <th>Cha</th>
      <th>Lvl</th>
      <th>Prof Bonus</th>
      <th>Skills</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @chars %> 
  </tbody>
</table>

<%= link_to "New char", new_char_path, class: "btn btn-success" %>

app/views/chars/new.html.erb
<% content_for :title, "New char" %>

<h1>New char</h1>

<%= render "form", char: @char %>

<br>

<div>
  <%= link_to "Back to chars", chars_path %>
</div>

app/views/chars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @char %>

<div>
  <%= link_to "Edit this char", edit_char_path(@char) %> |
  <%= link_to "Back to chars", chars_path %>

  <%= button_to "Destroy this char", @char, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :ability, style: "display: block" %>
    <%= form.text_field :ability %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :proficient, style: "display: block" %>
    <%= form.checkbox :proficient %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/_skill.html.erb
<div id="<%= dom_id skill %>">
  <p>
    <strong>Name:</strong>
    <%= skill.name %>
  </p>

  <p>
    <strong>Ability:</strong>
    <%= skill.ability %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= skill.score %>
  </p>

  <p>
    <strong>Proficient:</strong>
    <%= skill.proficient %>
  </p>

</div>

app/views/skills/edit.html.erb
<% content_for :title, "Editing skill" %>

<h1>Editing skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Show this skill", @skill %> |
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Skills" %>

<h1>Skills</h1>

<div id="skills">
  <% @skills.each do |skill| %>
    <%= render skill %>
    <p>
      <%= link_to "Show this skill", skill %>
    </p>
  <% end %>
</div>

<%= link_to "New skill", new_skill_path %>

app/views/skills/new.html.erb
<% content_for :title, "New skill" %>

<h1>New skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skill %>

<div>
  <%= link_to "Edit this skill", edit_skill_path(@skill) %> |
  <%= link_to "Back to skills", skills_path %>

  <%= button_to "Destroy this skill", @skill, method: :delete %>
</div>